compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: /weka-jd/prod/public/permanent/group_wangyizhong/wangyizhong/workspaces/peit/configs/deepspeed/zero_stage3_offload_peft_config.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
use_cpu: false
